--CREATING MASTER TABLE
CREATE TABLE PWD_MGR_MASTER(
    ID NUMBER,
    PLATFORM VARCHAR2(50) NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    CURRENT_PASSWORD VARCHAR2(50) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE, 
    CONSTRAINT PWD_ID_PK PRIMARY KEY (ID)
);

--CREATING HISTORY LOG TABLE
CREATE TABLE PWD_MGR_HISTORY_LOG(
    ID NUMBER,
    PLATFORM VARCHAR2(50) NOT NULL,
    PREVIOUS_PASSWORD VARCHAR2(50) NOT NULL,
    OLDER_PASSWORD VARCHAR2(50) NOT NULL,
    OLDEST_PASSWORD VARCHAR2(50) NOT NULL,
    CONSTRAINT PWD_ID_PK_2 PRIMARY KEY (ID),
    CONSTRAINT PWD_ID_FK
    FOREIGN KEY (ID)
    REFERENCES PWD_MGR_MASTER(ID)
);

--CREATING A SEQUENCE AND TRIGGER FOR ID
CREATE SEQUENCE PWD_MGR_SEQ START WITH 1; 

--DATE TRIGGER
CREATE OR REPLACE
TRIGGER TEST_USER.DATE_PWD_MGR_MASTER
BEFORE UPDATE ON TEST_USER.PWD_MGR_MASTER
FOR EACH ROW
BEGIN
--  CHECK FOR MODIFICATION OF CURRENT_PASSWORD:
    IF :NEW.CURRENT_PASSWORD != :OLD.CURRENT_PASSWORD THEN
       :NEW.CREATION_DATE := SYSDATE;
    END IF;
END;

